scan-type: source
ignore:
  - vulnerability: GHSA-vfj7-8cjw-p6xm
    include-aliases: true
    reason: 'Unfixable npm transitive vulnerability: braces (high severity) as of 2026-10-09'
  - vulnerability: GHSA-x5fp-wj9c-mxmx
    include-aliases: true
    reason: 'Unfixable npm transitive vulnerability: unknown (unknown severity) as of 2026-10-09'
  - vulnerability: GHSA-4mjr-xmp4-gh2g
    include-aliases: true
    reason: 'Unfixable npm transitive vulnerability: unknown (unknown severity) as of 2026-10-09'
output:
  - table
  - json
search:
  scope: squashed
quiet: false
check-for-app-update: false
