version: "3.7"
services:
  central-event-processor:
    build: .
    container_name: cep-central-event-processor
    links:
      - mongo
      - kafka
    ports:
      - "3080:3080"
    volumes:
      # override the default values with our own - this is because we can't set the kafka and mongo hosts dynamically
      - ./docker/central-event-processor/default.json:/opt/central-event-processor/config/default.json
    environment:
      - CSL_LOG_TRANSPORT=file

  ml-api-adapter:
    image: mojaloop/ml-api-adapter:latest
    container_name: cep-ml-api-adapter
    links:
      - kafka
    ports:
      - "3000:3000"
    volumes:
      # override the default values with our own - this is because the KAFKA_HOST env variable is ignored for some reason
      - ./docker/ml-api-adapter/default.json:/opt/ml-api-adapter/config/default.json
    # TODO: we should be able to remove this - I think the image command is broken
    command:
      - "node"
      - "src/api/index.js"
    
  central-ledger:
    image: mojaloop/central-ledger:latest
    container_name: cep-central-ledger
    links:
      - mysql
      - kafka
    ports:
      - "3001:3001"
    volumes:
      # override the default values with our own
       - ./docker/central-ledger/default.json:/opt/central-ledger/config/default.json
    environment:
      - CLEDG_DATABASE_URI=mysql://central_ledger:password@mysql:3306/central_ledger
      - CLEDG_SIDECAR__DISABLED=true


  mockserver:
    image: jamesdbloom/mockserver
    container_name: cep-mockserver
    ports:
      - "1080:1080"

  temp_curl:
    image: byrnedo/alpine-curl
    container_name: cep-temp-curl
    links:
      - mockserver
    volumes:
      - ./docker/wait-for-mockserver.sh:/opt/wait-for-mockserver.sh
    entrypoint: [ "sh", "-c" ]
    command:
      - /opt/wait-for-mockserver.sh
    environment:
      - MOCK_HOST=mockserver

  mongo:
    image: mongo
    container_name: cep-mongo
    ports:
      - "27017:27017"
  
  kafka:
    image: johnnypark/kafka-zookeeper
    container_name: cep-kafka
    # Disable kafka logging as it is far too verbose for debugging locally
    logging:
      driver: none
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ADVERTISED_HOST=kafka
  
  mysql:
    image: mysql/mysql-server
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      #this fixes the permissions issue, but docker-compose up will fail on first attempt
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-central_ledger}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-central_ledger}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true