@startuml
' declate title
title 10.5. Notification Action Flow
autonumber

' declare actors
collections "Notification-Topic" as TOPIC_NOTIFY
boundary "Central Event Processor" as CEP
control "Action Agent" as AA
database "CEP Store" as DB

box "Central Services" #LightYellow
participant TOPIC_NOTIFY
end box
box "Central Event Processing Service" #LightGreen
participant CEP
participant AA
participant DB
end box

' start flow
Group Action Flow
    activate CEP
    CEP -> AA: Recieves an action event
    activate AA
    AA -> AA
    note right of AA #lightGrey
        Evaluate action event
    end note

    alt Finish Signal "No"
        AA -> DB: Request **Action Object** details
        activate DB
        deactivate DB
        hnote over DB
            request
        end hnote
        note right of AA #LightGrey
            **Action Object** event details;
                Event action details,
                Hub notification details,
                DFSP notification details.
        end note
        AA -> AA
        note right of AA #LightGrey
            Prepare notification details
        end note
        AA -> DB: Request **Action Object** by same event details
        activate DB
        deactivate DB
        hnote over DB
            request
        end hnote

        alt No previous **Action Object** with same event detail
            AA -> DB: Store **Action Object**
            activate DB
            hnote over DB
                action
            end hnote
            AA <-- DB: Return result **actionId**
            deactivate DB
            AA -> AA
            note right of AA #LightGrey
                Schedule reset repetition for
                this **actionId** as per rules
            end note
            TOPIC_NOTIFY <- AA: Update topic with notification
            note left of AA
                {
                    from field = "SYSTEM"
                }
            end note
        else Previous **Action Object** with same event detail

            alt Repetition and notification interval allowed
                AA -> AA
                note right of AA #LightGrey
                    Update action.
                end note
            else Repetition and notification interval allowed not allowed
            end
            AA -> DB: Update **Action Object**
            activate DB
            deactivate DB
            AA -> AA
            note right of AA #LightGrey
                Schedule reset repetitions for **actionId**
                as per configuration rules.
            end note
            TOPIC_NOTIFY <- AA: Update topic with notification
            note left of AA
                {
                    from field = "SYSTEM"
                }
            end note
        end
    else Finish Signal "Yes"
    deactivate AA
    note right of CEP #LightGrey
        EXIT - No action required
    end note
    end
    deactivate CEP
end
@enduml
